services:
  frontend:
    build: .
    ports:
    - "5173:5173"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
    volumes:
      - backend-temp:/app/temp
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

volumes:
  backend-temp:
